# Generated by Django 5.0.6 on 2024-07-10 14:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('code_client', models.AutoField(primary_key=True, serialize=False)),
                ('nom', models.CharField(max_length=100)),
                ('adresse', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Produit',
            fields=[
                ('code_prod', models.AutoField(primary_key=True, serialize=False)),
                ('nom', models.CharField(max_length=100)),
                ('TVA', models.DecimalField(decimal_places=2, max_digits=5)),
                ('Prix', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
        ),
        migrations.CreateModel(
            name='Commande',
            fields=[
                ('num_cmd', models.AutoField(primary_key=True, serialize=False)),
                ('date_cmd', models.DateField()),
                ('design_cmd', models.CharField(max_length=255)),
                ('code_client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gest_cmd.client')),
            ],
        ),
        migrations.CreateModel(
            name='Ligne_cmd',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Qte', models.IntegerField()),
                ('prix', models.DecimalField(decimal_places=2, max_digits=10)),
                ('num_cmd', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gest_cmd.commande')),
                ('code_prod', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gest_cmd.produit')),
            ],
            options={
                'unique_together': {('num_cmd', 'code_prod')},
            },
        ),
    ]
